### ISSUE TITLE
The service doesn't work anymore (-)

### ISSUE THREAD

**Issue by selecadm** [konklone/shaaaaaaaaaaaaa#72]
Subj.

![image](https://cloud.githubusercontent.com/assets/10382329/6092782/0a00a7cc-af00-11e4-84e9-6a4ce74287ae.png)

![image](https://cloud.githubusercontent.com/assets/10382329/6092822/509b5424-af01-11e4-8079-add2b49e1e65.png)

![68](https://cloud.githubusercontent.com/assets/10382329/6092818/15c722a6-af01-11e4-902c-998cd86f1142.gif)

**Comment by konklone** [comment]
Thanks - it works again now. There's some kind of memory leak that eventually causes it to stop working, with this error:

```
Error: spawn ENOMEM
    at errnoException (child_process.js:1001:11)
    at ChildProcess.spawn (child_process.js:948:11)
    at exports.spawn (child_process.js:736:9)
    at Object.exports.execFile (child_process.js:618:15)
    at exports.exec (child_process.js:589:18)
    at Object.Shaaa.certs (/home/shaaaaa/shaaaaa/current/shaaaaa.js:101:5)
    at Object.Shaaa.from (/home/shaaaaa/shaaaaa/current/shaaaaa.js:168:11)
    at /home/shaaaaa/shaaaaa/current/routes.js:22:13
    at Layer.handle [as handle_request] (/home/shaaaaa/shaaaaa/current/node_modules/express/lib/router/layer.js:82:5)
    at next (/home/shaaaaa/shaaaaa/current/node_modules/express/lib/router/route.js:110:13)
```

And then if I restart the server, it works great...until it doesn't anymore. Help identifying and fixing the problem would be quite welcome!
